users:
  spy4x:
    displayname: "Anton Shubin"
    password: "$argon2id$v=19$m=65536,t=3,p=4$AdiUwaY1bck9uUby/AToQg$EeR/UsYyEM/6mQzbQu6M8o+nJbreoNx0SLQn0E6+2d0"
    email: anton@antonshubin.com
    groups:
      - admins
      - users
