networks:
  proxy:
    external: true
  default:
    external: true
    name: proxy

services:
  # Radicale is a lightweight CalDAV and CardDAV server for calendars, contacts, and tasks.
  # It provides a simple interface for syncing your calendar and contacts across devices.
  radicale:
    container_name: hl-radicale
    image: tomsquest/docker-radicale:latest
    user: "${PUID:-1000}:${PGID:-1000}"
    environment:
      - TZ=${TIMEZONE}
    volumes:
      - ${VOLUMES_PATH}/radicale/data:/data:z
      - ${VOLUMES_PATH}/radicale/config:/config:z
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 256M
          cpus: "0.25"
    security_opt:
      - no-new-privileges:true
    networks:
      - proxy
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=proxy"
      - "traefik.http.services.hl-radicale.loadbalancer.server.port=5232"
      - "traefik.http.routers.hl-radicale.rule=Host(`cal.${DOMAIN}`)"
      - "traefik.http.routers.hl-radicale.middlewares=robots-deny@file"
      - "traefik.http.routers.hl-radicale.entrypoints=websecure"
      - "traefik.http.routers.hl-radicale.tls=true"
      - "traefik.http.routers.hl-radicale.tls.certresolver=myresolver"
