name: ${PROJECT}

networks:
  proxy:
    external: true

services:
  # Gatus - Modern, lightweight health check & status page
  # YAML-configured monitoring with ntfy alerting
  # https://github.com/TwiN/gatus
  gatus:
    container_name: gatus
    image: twinproduction/gatus:latest
    environment:
      - RSPAMD_USERNAME=${BASIC_AUTH_USER}
      - RSPAMD_PASSWORD=${RSPAMD_PASSWORD}
      - TRANSMISSION_USERNAME=${MONITORING_BASIC_AUTH_USER}
      - TRANSMISSION_PASSWORD=${TRANSMISSION_PASSWORD}
      - NTFY_TOKEN=${NTFY_AUTH_TOKEN}
      - NTFY_URL=${NTFY_URL}
      - DOMAIN=${DOMAIN}
    volumes:
      - ${GATUS_CONFIG_PATH}:/config/config.yaml:ro
      - ./.volumes/gatus/data:/data
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 64M
          cpus: "0.1"
    security_opt:
      - no-new-privileges:true
    networks:
      - proxy
      - default
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=proxy"
      - "traefik.http.services.gatus.loadbalancer.server.port=8080"
      - "traefik.http.routers.gatus.rule=Host(`uptime.${DOMAIN}`)"
      - "traefik.http.routers.gatus.entrypoints=websecure"
      - "traefik.http.routers.gatus.tls=true"
      - "traefik.http.routers.gatus.tls.certresolver=myresolver"
