# Loads default set of integrations. Do not remove.
default_config:

# Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes

# Text to speech
tts:
  - platform: google_translate

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

# HTTP configuration for reverse proxy support
http:
  use_x_forwarded_for: true
  trusted_proxies:
    - 172.17.0.0/16 # Docker bridge network
    - 172.18.0.0/16 # Proxy network
    - 172.19.0.0/16 # Proxy network (additional range)
    - 127.0.0.1 # Localhost
    - ::1 # IPv6 localhost
