name: ${PROJECT}

networks:
  proxy:
    external: true
  default:
    external: true
    name: proxy

services:
  # IT-Tools - Collection of handy dev & sysadmin tools
  # PDF manipulation, image conversion, encoding/decoding, etc.
  # https://github.com/CorentinTh/it-tools
  it-tools:
    container_name: it-tools
    image: corentinth/it-tools:latest
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: ${IT_TOOLS_MEM_LIMIT:-128M}
          cpus: ${IT_TOOLS_CPU_LIMIT:-0.2}
    security_opt:
      - no-new-privileges:true
    networks:
      - proxy
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=proxy"
      - "traefik.http.services.it-tools.loadbalancer.server.port=80"
      - "traefik.http.routers.it-tools.rule=Host(`it-tools.${DOMAIN}`)"
      - "traefik.http.routers.it-tools.entrypoints=websecure"
      - "traefik.http.routers.it-tools.tls=true"
      - "traefik.http.routers.it-tools.middlewares=auth"
      - "traefik.http.routers.it-tools.tls.certresolver=myresolver"
